name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  solhintci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Solhint
        run: |
          npm install --global solhint@5.0.5
      - name: Solhint
        run: |
          solhint 'src/**/*.sol'

  check:
    strategy:
      fail-fast: true

    name: Foundry CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: forge build
        run: |
          forge build --sizes
        id: build

      - name: forge test
        run: |
          forge test -vvv
        id: test

      - name: forge coverage
        run: |
          script/coverage.sh
        id: coverage
