name: CI

env:
  BASE_SEPOLIA_ETHERSCAN_API_KEY: ${{ secrets.BASE_SEPOLIA_ETHERSCAN_API_KEY }}
  BASE_SEPOLIA_RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC_URL }}
  FOUNDRY_PROFILE: ci

on:
  push:
    branches: [ main ]
  pull_request:
    # TODO: remove this - this should only run on main, not in pull requests
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: true

    name: Deploy to Testnet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Base Sepolia Testnet Deploy
        run: |
          forge clean && forge script script:UpgradesScript.s.sol --rpc-url base_sepolia --private-key ${{ secrets.TESTNET_DEPLOYER_PRIVATE_KEY }} --broadcast --verify --sender ${{ secrets.TESTNET_SENDER }}
