name: Deploy to Testnet

env:
  BASE_SEPOLIA_ETHERSCAN_API_KEY: ${{ secrets.BASE_SEPOLIA_ETHERSCAN_API_KEY }}
  BASE_SEPOLIA_RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC_URL }}
  PRIVATE_KEY: ${{ secrets.TESTNET_DEPLOYER_PRIVATE_KEY }}
  SENDER: ${{ secrets.TESTNET_SENDER }}
  FOUNDRY_PROFILE: ci

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ stage ]
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: true

    name: Deploy to Testnet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Base Sepolia Testnet Deploy
        run: |
          forge clean
          TRANSPARENT_PROXY_ADDRESS=0x5cF974E2fC8C4458da4E2F687E3551Be9089a9e3 forge script script/UpgradesScript.s.sol --rpc-url base_sepolia --private-key $PRIVATE_KEY --broadcast --sender $SENDER
